version: "3"
services: 
  bot:
    environment:
      BACKEND_URI: http://backend:8080
      API_TOKEN: ${API_TOKEN}
    container_name: bot-futbol-matches
    build: ./bot
    image: bot-futbol-matches:latest
    pull_policy: build
    networks:
      - public
  backend:
    environment:
      DB_CONNECTION_URI: ${DB_CONNECTION_URI}
      REDIS_URI: "redis:6379"
      REDIS_NAME: ${REDIS_NAME}
      REDIS_PASS: ${REDIS_PASS}
    container_name: api-futbol-matches
    build: ./backend
    image: be-futbol-matches:latest
    pull_policy: build
    ports:
      - "8080:8080"
    networks:
      - backend
      - public
  mongo:
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    container_name: db-futbol-matches
    image: mongo:6.0.2
    restart: always
    ports:
      - "27017:27017"
    networks:
      - backend
  redis:
    container_name: metrics-futbol-matches
    image: 'redislabs/redistimeseries:1.8.2'
    ports:
      - '6379:6379'
    networks:
      - backend

networks:
  backend:
    driver: bridge
  public:
    driver: bridge